### ISSUE TITLE
Details Templating - High Level

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/r4design#17]
Guts by @RyanCoulsonCA 

This outlines a few methods we could use to implement custom templating for the details panel. These ideas are mostly for discussion. We can make modifications as necessary.

Feel free to leave any feedback or ideas you come up with while reading!

## Idea 1: Binding Layer to Template

If the user wants to use a custom template for a layer, they will need to define it in the configuration file. This is similar to how we implemented custom templates in RAMP2, with some small modifications to make it work with the fact that the details fixture may not be added to the map.

Layers that are added through the configuration file are already defined with an `id` that they can be referenced by. This makes adding a custom template to the layer pretty straight-forward (see the example config snippet below): 

```
{
    ...,
    layers: [
        ...
        {
            id: "My-Layer-ID",
            layerType: "esriFeature",
            ...
        }
        ...
    ],
    fixtures: {
        identify: {
            templates: {
                "My-Layer-ID": "<custom-vue-component>"
            }
        }
    }
}
```

The user would then need to register `<custom-vue-component>` on the host page using `RAMP.component('<template-component-name>', <VueConstructor>)`.

Upon receiving an identify result, the details panel will check to see if there's a custom template defined for the layer in the configuration file. If there is, the template will be loaded and displayed. If no custom template is defined, the default template for the layers return type will be shown.

This would work for layers defined through the config file. We would still need to implement a way to add custom templates to layers that are added directly from the host page. An easy solution would be to add a function to the details API, such as: 

 > `this.$iApi.fixtures.get('details').setCustomTemplate(<layer_id>, <component>);`

## Idea 2: Override Default Type Template

We define a `customMapping` attribute in the config file that allows us to bind a specific return type to a template (originally proposed by Aleks). When the details panel opens, it will look at the layers result type and then check to see if there's a template bound to it. If so, it will render it and pass the layer information through to the template.

```
fixtures: {
    identify: {
        customMapping: {
            "<layer-format-name>": "<template-component-name>",
            "<another-layer-format-name>": "<another-template-component-name>",
        }
    }
}
```

We run into a problem here if we want to use different templates for layers that have the same result type (e.g. we have two feature layers with the `esri` return type, but we want them to use different templates). I've come up with two methods to get around this:

### Add an option to the layer config that allows us to override its return type. 

(initially proposed by James)

The `IdentifyResult` object returned from identify contains a `result type` attribute that's provided by the layer. We could add in a config option that allows us to modify the type value that identify returns.

For example, we could define a layer in the config file like this:

```
{
    ...,
    layers: [
        {
            id: "My-Layer-ID",
            layerType: "esriFeature",
            returnType: "myCustomType"
            ...
        }
        ...
   ],
   ...
}
```

And then when the identify result is returned for this layer, the object would look like this:

```
{
    data: [...],
    format: "myCustomType"
}
```

If we did something like this, we wouldn't need to worry about having multiple templates for one return type. We could create our own return types and assign templates as needed:

```
fixtures: {
    identify: {
        customMapping: {
            "myCustomType": "<template-component-name>"
        }
    }
}
```

This method works, but comes with a trade-off: it won't work if we want to have multiple templates for a single layer (if we want to show templates based on an attribute value, for example).

### Allow binding multiple templates to one result type.

Instead of just allowing one template to be bound to each result format, we can allow a list of templates to be bound to a format by providing a template and an identifier, for example:

```
fixtures: {
    identify: {
        customMapping: {
            "<layer-format-name>": [
                {
                    id: "template-1",
                    template: "<template-1>"
                },
                {
                    id: "template-2",
                    template: "<template-2>"
                }
            ],
            "<another-layer-format>": [...],
            ...
        }
    }
}
```

This also requires that we add an attribute to the layer config that allows us to specify which template we want to use. 

```
{
    id: "My-Layer-ID",
    layerType: "esriFeature",
    customTemplate: "template-1",
    ...
}
```

On receiving an identify result, the details panel will check to see if a custom template is defined for the layer and displays it. If no template is specified in the layer config, the default template would be displayed.

## Idea 3: Host Page Only Approach

We could skip the config file completely and implement a host page-only approach that requires the user to use the details API if they want custom templating. The details store would keep track of which template to display for each layer.

We implement two functions `addTemplate(id: string, template: VueComponent)` and `removeTemplate(id: string)`, which are accessed directly through the details API.

When adding a template, the user registers their Vue component using `RAMP.component('<template-component-name>', <VueConstructor>)`. They then use `addTemplate`, providing the layer ID and the Vue component as parameters. Once this is done, making an identify request on the layer will display the new template.

`addTemplate` should allow for templates to be overwritten if called on the same layer ID twice, allowing us to display different templates on the same layer if needed.

To remove a template, simply call `removeTemplate` and provide the layer ID. Making a call to identify on this layer would then just show the default template.

This method probably isn't ideal as a "primary solution", but could be supplementary to one of the other ideas.

### Any other suggestions?

**Comment by james-rae** [comment]
Feedback by @spencerwahl 

I think I prefer idea 1, the only benefit to 2 seems to be a few less config lines at the cost of adding another layer of configuration to then have per-layer templates again.

And for discussions sake; there is also the (probably not good) option of "if you want details to look different use a new plugin". One argument is that maps that want to control how the details look probably want to control the entire panel's display and not just the little section each point gets in a list. CCCS as one example would probably use a new plugin rather than details templates if both were options. If I remember correctly there were still things that had to be compromised from the design due to elements outside of the template. That being said its probably not a good reason to say "no templates".

**Comment by james-rae** [comment]
Feeback by me

Non UI person weighing in: if spinning up a new fixture (and we provide a little how-to doc) is significantly easier than building some compile-process-render framework, I'd say it's a valid option. I don't know the difficulties that vue would present for templating so can't give weights to the options

**Comment by AleksueiR** [comment]
@james-rae 
>if spinning up a new fixture (and we provide a little how-to doc) is significantly easier than building some compile-process-render framework,

Yes, making fixtures is easy, but the identify fixture does more than just render data in a template. Think of RAMP2. The identify panel displays a list of layers that have identify results, it groups the results and lets you look at each one separately or open several, and it lets you open a full-screen modal with the identify results data (it also highlights features on the map when you expand results).

R4 identify fixture doesn't have to do all that, but at the very least it should display a list of all identify results from a click. If we say that the host page should just make its own identify fixture, someone will need to re-create the logic for grouping and displaying identify results. I think that would be too much to ask if a person just wants to change how a single field is rendered, for example. I think we should provide a templating option here, and the host page authors are always welcome to spin up a new fixture and do whatever if they so desire.

I prefer `Option 1` as it seems the most flexible. `Option 2` lets you define template for layer types, but how common would that be? One case I can think of is dynamically added layers, but if we implement the `setCustomTemplate` API call or something like that, that's no longer a problem. Yes, the config might have several more lines with `Option 1`, but it should result in lower complexity.

**Comment by james-rae** [comment]
Agreed. My "spinning up a new fixture" was assuming copying the original fixture and modding the 3rd panel, but wasn't explicit. 
But even that is a chore if you just want a minor change to panel 3.

**Comment by AleksueiR** [comment]
> copying the original fixture and modding the 3rd panel, but wasn't explicit.

This is not as easy as it seems as well. Since our identify fixtures and part of the core project and written in ts/vue, you can't take source code; need to take compiled js code, and that's unreadable. To create a true copy, you need to create a new ts/vue project with our fixture code and our setup, modify it and compile and only then load in the host page. Lots of work unless we provide a detailed template for this.

That is actually a good question. Do we need to provide a guide/template for someone wanting to copy/mod a core fixture? They can always clone the whole r4mp repo and do it this way.
