### ISSUE TITLE
Config Manipulation

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/r4design#18]
### RAMP2 Bookmark

- Config loads
- Bookmark is analyzed.
- Matching bookmark layers to config layers, updating config values
- Removing config layers that don't exist in bookmark
- RAMP consumes modified config

### RCS

- Config loads
- RCS is called with URL key params
- Asynch result from RCS. Values are inserted into config layer array.
- RAMP consumes modified config

### Custom Page Modifier

Examples: [CESI](http://maps-cartes.ec.gc.ca/indicators-indicateurs/) adds layers based on outside selection box. [Climate Action Map](https://climate-change.canada.ca/climate-action-map/) uses custom url to preserve zoom level and identify point (though appears not to be working well). [CCCP](https://climate-viewer.canada.ca/climate-maps.html#/) would inject custom legends and layers based on parameter selections.

- Config loads
- Something outside the app manipulates the config
- Map loads

## General Needs

Based on the above use cases and general brain-thinking, things we probably want are

- Ability to intercept the config prior to RAMP using it to start the main processes (map creation, layer load, etc).
- Ability to have multiple things manipluate the config, in specified order (think RAMP2 FGP: Config -> RCS -> Bookmark)
- Interception chain must support async (e.g. loading data from RCS, bookmark loading state from service)
- Some type of timeout? If one service is down, should app fail to load?
- Ability to modifiy all of the config, not just the layers

## Current Code

- Config is supplied as part of the constructor for creating a RAMP Instance.
- Config can contain fixture specific nuggets of config
- Fixtures are added to the instance after it exists (i.e. config is already in the store). In most cases is done by host page. We also have an external fixture that adds itself (see Iklob). Fixtures execute their `added()` routine.
- *In Beta*: as map and layer config items appear, watches in `esri-map.vue` create map and layer objects.
- *Coming soon*: a config class that might do defaulting, provide nicer access to stuff.
- *Not yet designed*: auto-loading of out-of-box fixtures. I.e. if you just run RAMP with no code, you get standard everything. Maybe we don't provide this and boiler-plate fixture adds always need to be on page code?

## Paradigm 1: Have everything done outside of RAMP

All config interception and manipluation happens prior to the config being fed to a RAMP instance. The `RAMP` api could provide standalone tools to help manipulate the config. E.g. expose the config class, give it some CRUD type methods.

Pros:

- Ramp core cares not.

Cons:

- Would mean we could not bundle a common re-usable thing into a fixture.
- Page would have to host all pre-config logic. Not great, if you look at the amount of code the bookmark module has.

## Paradigm 2: Config manipulation as part of the starting process

Currently the loading flow is

1. Make instance, config as constructor.
2. Config enters the store
3. Add fixtures.
4. Fixtures execute their `added()` routine.

If we want fixtures to be able to manipulate the config, we might need something extra to allow the scheduling.

**Idea 1. Start function**

1. Make instance, config as constructor. Config could remain raw, or be parsed into typed config. The map does not start up.
2. Add fixtures. Fixture startup code can register for pre-config if they desire.
3. Register any custom page functions for pre-config, if desired.
4. Call `instance.start()`
5. The instance does a pre-config step. All things registered for pre-config get run in order. They are asynch so it's a chain of one promise resolves, the next promise starts. Pre-config ends when last promise resolves.
6. After pre-config, the config is considered finalized and the process that instantiates the map, layers, begins

Pros: 

- Allows flexibility for timing, giving the author can call `start()` when they want, and can control the order fixtures get registered.
- Can also support a one-off function from outside that returns a promse, this can be registered for the pre-config step.

Cons:

- Yet another required function on the client boilerplate.
- Order of registration can be controlled, but if two things had to play in concert with each other it could get complex (e.g. how RCS would load, then bookmark would process, but bookmark might have to call RCS again if it had new keys in it).

**Idea 2. Load at Constructor**

Would extend the instance constructor to be `Instance(config, array_of_fixtures)` where any fixtures in the array would be considered pre-config worthy.

1. Make instance, config and fixtures as constructor. Config could remain raw, or be parsed into typed config. The map does not start up.
2. Constructor fixtures either all register for pre-config on their startup, or fixture implements a `preConfig(): Promise<void>` method that they override with any steps.
3. All the pre-config asynch is called and waited upon. Config is updated during this process.
4. Remainder of normal constructor startup continues
5. Add fixtures that were not config manipulators in normal way.

Pros: 

- Wraps all the preconfig stuff in the constructor, keeping things in line with how they are now.

Cons: 

- Seems awkward to have to load fixtures in separate ways depending on if they support one use case (of many use cases that fixtures address). 
- Forces config manipulation to be in a fixture.

## Paradigm 3: Bind-o-Matic

We accept there is no "pre-config" step, and let bindings react to all config changes as they happen. Example startup flow.

1. Make instance with config. Instance initializes as it currently does.
2. Add fixtures.
3. Fixture startups manipulate the instance config as they please.
4. Client code manipulates the instance config as it pleases.
5. As the instance config changes, our vue/vuex magic notices properties changing, array elements getting added and removed, and updates the app accordingly.

Pros:

- Eliminates any fancy loading steps. Things just do as they please. 
- Supports config manipulation after startup / mid-session.

Cons:

- Possible race conditions with multiple fixtures attempting asynch updates to config.
- Prone to inefficiencies; as an example, if instance starts up in Lambert then the bookmark fixture modifies the state to Mercator, will be loading things twice and likely see it start-die-start on screen.
- Our vue/vuex/configclass bindings may not be powerful enough to seamlessly update everything just by updating the config object.

## Paradigm 4: The Mystery Paradigm

This is where you tell me something better. You got this, champ!

## Further Pontifications

RAMP2 used bookmarks to handle things like language change and projection change.  Ideally, with `vuex` we will be able to just smack whatever is in the state and have things work. This might involve a reload of the map but ideally no need to "bookmarking". 

One potential snag is when a language changes and we are required to use a different layer set based on the language. Off the cuff this feels like a "load a new config" scenario, but also there is a desire to have the previous state of things exist. This brings up the good old grousey debate of "does changing language mid session make sense?", and is it worth investing handling such an elitist feature.

**Comment by james-rae** [comment]
Feedback from @spencerwahl 

I was under the impression that `core` would have a "here's my state" method, similar to a bookmark but the host page or a fixture would be in charge of converting state object to a url, or putting it in local storage, etc.

`core` would then have a "give me state" method that updates the config, stores, whatever with the info in the state object. This could also be an optional param on a `loadConfig` type method or on the RAMP constructor along with the actual config.

**Comment by james-rae** [comment]
Retort from me

This is still on the table (and I did forget about it, to be fair). Reasonable if this is "our" bookmark. But it is limited; local storage is...local, state service needs a service, and i'll be real impressed if we can fit all the state on the url.

I'm not suggesting we write the old bookmark fixture (good riddance I say). In hindsight should have focused less on the bookmark scenario in the writeup.

More putting forth the question "should our startup routine support asynch config modification before the core acts on it?" in anticipation of any of the use-cases arising (for us or a 3rd party).  Paradigm 1 is effectively "no". 2 is "yes". 3 is "no" but we have more complex support internally.

If we can get url bookmarkstate or a free storage service, it could be "alternate bookmark" drops off the use-case list and out-of-box is champ.

And us as a team saying "state snapshot bookmarks and paradigm 1" is a valid path forward

**Comment by AleksueiR** [comment]
## Paradigm 2
### Idea 3: Fixture hook

We can add another hook (`pre-config`) to the fixture class that is called before the config is parsed, and we can even make it blocking and require the fixture to execute a passed in `done` callback function to indicate that the fixture is done with its `pre-config` steps.

This approach doesn't require the host page make an extra call (`instance.start()`) or to load fixtures differently depending on whether there is a "bookmark state" or not.

Also, if the host page wants to do some extra config manipulation, it can spin up a headless fixture with a single `pre-config` function whose only purpose is to modify the config.

---

Idea 2 has this as a con: 
> Forces config manipulation to be in a fixture.

Why is this a con? I think it's good to not group all the bookmark processing in a single place like it was done in R2.

**Comment by james-rae** [comment]
The hook idea is interesting. The only question I would have is would things be executed in a random or concurrent order.  E.g. if we were forced to do the data catalog again and needed Bookmark then RCS, would this support that?

For the con comment, the other solutions let you just have a function on the host page if you want to do something with the config. Your comment about a headless fixture addresses this, though seems more effort/boilerplating then just `const myFunc = () => {do stuff}`. So not a hard con.

**Comment by AleksueiR** [comment]
> would things be executed in a random or concurrent order?

Right now, I think it would be a random order as fixtures are loaded dynamically (apart from ones supplied by the host page) and the loading order might not be the same as the order fixtures were added in. However, we can easily enforce the order fixtures are instantiated. This might slow down initial RAMP loading though if one of the fixtures is slow to load.

Could you please explain the RCS example some more and why do we need a strict order in this case?

> our comment about a headless fixture addresses this, though seems more effort/boilerplating then just const myFunc = () => {do stuff}. So not a hard con.

Creating a headless fixtures is almost as easy as that, thanks to all the boilerplate being abstracted to the guts of RAMP core:

```js
class HeadlessFixture {
    preConfig(config) {
        // do stuff with the config
    }
}

rInstance.fixture.add('headless', HeadlessFixture);
```

**Comment by james-rae** [comment]
Blank catalog: 
url is `www.cat.com/page.html`. 
Load flow is: read base config; start ramp

RCS catalog:
url is `www.cat.com/page.html?keys=dog,guts`. 
Load flow is: read base config; asynch fetch key data from rcs; insert into config; start ramp

Bookmarked RCS catalog:
url is `www.cat.com/page.html?rv=ENCODEDJIBBERISH`. 
Load flow is: read base config; decode bookmark, apply change vectors to config; recognize rcs layers in bookmark data; asynch fetch key data from rcs; insert into config; start ramp

So this is just an example, and is going by old paradigms. There could be other ways to orchestrate concepts of bookmarking and a remote config snippet store that allow this in one shot. 

But this design is to anticipate as many possible scenarios we might encounter; so was thinking control over order in general would be a good thing to have.

Since your headless fixture is far easier than I thought (I was looking at the sample external fixtures that needed files, etc), maybe an orchestration approach could work

```js
class LoadmasterFixture {
    preConfig(config) {
        bookmarkFixture.doStuff().then(() => {
             rcsFixture.doStuff(bookmarkstuff).then(() =>{
                  report done;
             })
        })
    }
}

rInstance.fixture.add('loady', LoadmasterFixture);
```

I'm unsure how easy it is for a headless fixture to just grab other fixtures, but if they are added I would guess they can get a reference via `instance.fixtures()`

**Comment by james-rae** [comment]
Another question is how does the `pre-config` hook know when to trigger? Config gets loaded during the instance constructor (?), and fixtures are added after. This is why I was proposing the `instance.start()` type idea.

**Comment by AleksueiR** [comment]
> Load flow is: read base config; async fetch key data from rcs; insert into config; start ramp

Does this require RAMP re-loading? If this is just inserting new layers into the map, we don't technically need to do it before the startup sequence. We can insert layers anytime we want.

> But this design is to anticipate as many possible scenarios we might encounter; so was thinking control over order in general would be a good thing to have.

I was thinking more about enforcing order in which fixtures are added:
```js
rInstance.fixture.add('appbar');
rInstance.fixture.add('mapnav');
rInstance.fixture.add('snowman');
```

> Another question is how does the pre-config hook know when to trigger? Config gets loaded during the instance constructor (?), and fixtures are added after. This is why I was proposing the instance.start() type idea.

This is a very good point. 🤔 We can probably change the order things are happening in the core, but this will create ambiguity--what if a feature is added five second later? Does it mean that its `pre-config` hook is useless now? This sounds like a race condition 😐

Is this a hard requirement to modify the config before the map is created? Could we move the changes after the map is initialized? I understand that changing basemap projection in such case will trigger a full map reload, but what are other thing that can force map reload?

**Comment by james-rae** [comment]
I don't think we have any "hard requirements" given this this is all behind the curtains right now. If we say "we should be able to migrate our existing apps" then it is, though we can always achieve things with bad hacks on page code (i.e. do all config processing outside of ramp before making an instance). But that seems poor.

The bookmark/rcs sample can be a bit misleading as it focuses on layers. Our solutions to this challenge should be considering anything in the config being modified, not just layers. Also the bookmark can be removing layers, so it's better to have it gone before processing; though load then remove will get the end result, but with inefficient and more complex code.

For the fixture order being the order of processing, I think this is ok, since we have the orchestrator fixture option if complex scheduling is required.

RACE DAY.
Tricky, dirty business.  A brief summation of the options on the table (I don't like any of them)

**Don't support**
- easiest
- "ramp cant do it" scenario
- potentially pushes complex and re-usable code into host page; much better suited to live in a fixture

**Start function**
- very easy, solves race problem
- every single page requires start call, regardless. ugly solution.

**Ridiculous constructor**
- does appear to solve things
- takes one of the key and straightforward startup flows and makes them wacky and obtuse. ugly

**Totally re-envision the startup process**
- ugh.
- please no.


### A different idea

This comes from the `data-rv-wait="true"` flag from RAMP2. Take the concept of the start function, but make it optional. 

**Scenario 1: Happy standard ramp**

No config nonsense required. Page code is clean. If we have something like the state-smasher bookmark, it would probably work in this configuration.

```js
function initRAMP() {
    var rInstance = new RAMP.Instance(config);
    rInstance.fixtures.add(fancyfixture);
}
```

**Scenario 2: Ramp needs some complexity**

We can enable the start function. Solves the races, only need the call when its useful.

```js
function initRAMP() {
    var rInstance = new RAMP.Instance(config, {startRequired: true});
    rInstance.fixtures.add(fancyfixture);
    rInstance.fixtures.add(imesswithconfigsfixture);
    rInstance.start();
}
```

**Comment by AleksueiR** [comment]
> **Scenario 2: Ramp needs some complexity**
> We can enable the start function. Solves the races, only need the call when its useful.

:+1:

**Comment by spencerwahl** [comment]
>A different idea
> [...]

seems good to me ✔️
