### ISSUE TITLE
Vuex store modules and Legends

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/r4design#3]
Posted in chat by @spencerwahl  and @AleksueiR 

## Some terminology

- Vuex store has `modules` (sections of the store where related data is kept)
- Vue has `components` (usually UI elements with some logic; components can be deeply nested)
- RAMP has `core` and `modules`
  - `core` parses config and renders the layers with the basemap (plus some other things)
  - `modules` will be responsible for anything that is not `core` (legend, datatable, export, etc.)
  - some modules will written by written by us (core modules)
  - some modules will be written by normal people (external modules)

To avoid confusion between RAMP modules and Vuex store modules when talking about modules, please clarify which module you have in mind.

## How we think it should work

Generally, each RAMP core module will have a corresponding Vuex store module to fetch the data from, but RAMP modules will have access to all Vuex store modules if that's needed.

Legend/Layers seems to be the most complicated part of RAMP. Lets go through some examples.

Startup:
- RAMP receives JSON configuration, `RAMP core` separates sections and places them in the `Vuex config module`. After that, the original config cannot be changed and doesn't do anything useful.
- `RAMP legend module` reads the legend config from the `Vuex config module`, generates a legend structure (with Legend entries and groups and other shiny things) (this parsing function might need to be pulled into the core, so any custom legends can reuse it), and stores it in the `Vuex legend module`.
- From that legend structure, the `RAMP legend module` creates the legend UI.

Replacing/adding to the legend:
- To use a new JSON legend config a function on the `Vuex config module` will be called. The above startup process will then see a new legend config and create a new legend structure and so forth.
- To add a single legend item we either pass a legend item snippet to the `Vuex legend module` or call a function on `Vuex legend module` that will handle the creation of a certain type of legend item.

User clicking a button on the legend:
- User clicks `remove layer`
- `Vuex legend module` is asked to delete the legend entries and figure out which actual layers were attached to the legend entries.
- `Vuex layer module` is told to delete the proper layers from the layer list.

Non legend modules seem much more straightforward.

For instance the `Vuex details module` will pretty much only store the data the details panel should show. Extracting the useful stuff from the raw data into what the template wants should happen in the `RAMP details module`.

**Comment by james-rae** [comment]
Was thinking of entertaining other words for RAMP modules (`unit`, `intention/extention/outention`, `component`, etc) but none seemed worthy.
Am wondering how people feel about adopting a shorthand of vmodule and rmodule for unofficial chats?  That said, kerning is already making rmodule look weird. Rmodule. rModule. ArrModule :sailboat:
No biggie either way, we can get used to writing the full thing.
All other stuff in the post looks grand.

**Comment by AleksueiR** [comment]
@spencerwahl and I thought about using something else to replace "module", but couldn't find any good synonyms ("chunk" anyone?). 

What if we pick some nonsense word to mean "module" for RAMP instead using this lovely generator of pronounceable words: http://www.name-generator.org/ ?

**Comment by AleksueiR** [comment]
Suggestions:
- `gear` -- `LegendGear`, `BookmarkGear`
- `gut` -- `LegendGut`, `BookmarkGut`
- `cog` -- `LegendCog`, `BookmarkCog`
- `o-tron` -- `LegendOTron`, `BookmarkOTron`
- `brick` -- `LegendBrick`, `BookmarkBrick`
