### ISSUE TITLE
GeoAPI to Vuex Legend Shouting & Handwaving

### ISSUE THREAD

**Issue by james-rae** [ramp4-pcar4/r4design#4]
Proposal an idea of a way to do it, can give rise to better ways. We will use a Dynamic Layer (known as Map Image Layer in ESRI 4) as the example.

Discussing this gave rise to another discussion, captured at https://github.com/ramp4-pcar4/r4design/issues/5

# Current RAMP2 Approach

## GeoAPI Object

- GeoAPI Layer object ("Record") represents the physical map layer (i.e. the image on the map, and the root of the layer).
- Record also contains a collection of children representing the logical layers (i.e. feature classes of data, something that can open a table, have a symbology stack, etc).
- Record exposes a function that will return a tree structure of the layer. It only does this for Dynamic Layers, the function doesn't exist on other types
- A lot of stuff is not populated until the layer can get metadata from the map server (async), including the child information
- Exposes an interface/proxy upon request. The interface encapsulates a "layerish thing". So you can have a proxy for the root and for the children (i.e. they both can have visibility toggles, names, settings).

## Legend

- Legend has custom logic on how to handle the various layer types (e.g. more simple code for Feature Layer, WMS, etc)
- Requests a GeoAPI proxy for the root while the layer is loading. Creates a legend item bound to the proxy
- After successful load, gets the layer tree structure (non-Dynamic would default to a simple one-layer UI).
- Generates GeoAPI proxies and legend structures for the tree, binds the two

# R4MP Approach - One Possibility

## Squad Goals

- GeoAPI Layer object is intuitive to use
- GeoAPI Layer object is as consistent as possible across all layer types.
- No interface/proxy from the GeoAPI
- Legend respects the Ramp Module / Vuex Module design proposals

## The Flow

- GeoAPI Layer object is created at request of Ramp core or Ramp layers module. Its state property will indicate loading
- Ramp Legend module is made aware of the Layer (fine details to come, a pointer to the Layer object would make sense for now). It generates an object in Vuex Legend module to render the placeholder
- Ramp Legend module reacts to the layer finishing loading
- Ramp Legend module extracts tree structure from Layer object. Creates appropriate objects in Vuex Legend module to support layer tree. Overwrites the original placeholder object.

## Unanswered Things

How does the Vuex Legend module get synchronized when something else changes the layer?

- GeoAPI emits event/observable. Ramp Legend module hears event, does a mutation on Vuex Legend module?
- A different configuration of emitters & listeners?

Dealing with sublayers of a Dynamic Layer

- Will assume for now the first bullet of the above synchronization question
- Event from GeoAPI contains appropriate parameters to target which thing changed. E.g. if visibility changes, need to know if it was the root or one of the child layers.
- Handler (Ramp Legend module for now) interprets the event and knows which mutation to invoke.
- Alternate approach could be events and handlers directly on the child layers. Means more events wired up, but no "which array index / tree node do I need to target" code.
- Other ideas?

## Vague Justifications

Having the GeoAPI Layer object and the Vuex Legend module objects be different is to support the wise design philosophy ( https://github.com/ramp4-pcar4/r4design/issues/1 )

> modules should be replaceable and RAMP core will not know either way

**Comment by AleksueiR** [comment]
> Dealing with sublayers of a Dynamic Layer
> Event from GeoAPI contains appropriate parameters to target which thing changed. E.g. if visibility changes, need to know if it was the root or one of the child layers.

If we give all the layer-like objects (feature layers, and dynamic layer children) distinct ids, we can target any Vuex layer object directly, without mucking around with array indexes.

An event from GeoAPI might also contain all the properties that have changed for the layer, so there is no need for multiple event types, etc.:
```json
// update event/observable emitted by GeoAPI
{
    "layerUid": "0933d350",
    "data": {
        "opacity": 0.4,
        "visibility": true,
        "boundingBox": false
    }
}
```

If property names in the event and Vuex layer object are mapped one-to-one and have the same names, the event handler (Vuex action/mutation) can just override old state values with new ones without having to parse and understand what actually changed. So, only a single event type (`update`) is needed from GeoAPI to keep Vuex in sync.

Also, the Vue Legend object will have additional, UI-only properties (like whether the group or layer symbology stack is expanded or not) which will not be synced with GeoAPI layers, and it would probably be a good idea to keep them separate.

**Comment by james-rae** [comment]
Overall this sounds ok. Internally its not an issue to maintain unique ids on the geoApi objects, and can include them in the layer tree that all GeoAPI Layer objects expose.

One minor thing to note is that to the client, the GeoAPI layer is one object with index-able properties. But if we use the event schema you have proposed, it becomes irrelevant (and likely simplifies things from a synch standpoint).  If need be, I can also enhance the index-able properties to accept string values, strings being interpreted as Uids, numerics being interpreted as classic indexes.
